url: 'https://akylas.github.io'
baseurl: ''
title: Akylas
email: contact@akylas.fr
description: Mobile apps developer and Open Source contributor
people:
  - name: Martin Guillon
    pic: 2
    position: Founder / Developer
    social:
      - title: linkedin
        url: 'https://www.linkedin.com/in/martinguillon/'
      - title: github
        url: 'http://github.com/farfromrefug'
social:
  - title: bitbucket
    url: 'http://bitbucket.org/farfromrefug'
  - title: github
    url: 'http://github.com/farfromrefug'
address:
  - line: 38000 Grenoble
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-admin
